#!/bin/bash

source "$HOME/.config/sketchybar/themes/evergarden.sh"
source "$HOME/.config/sketchybar/icons.sh"
source "$HOME/.config/sketchybar/plugins/icon_map.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"

FONT="SF Pro"
PADDINGS=3

launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

bar=(
    height=30
    color=$TRANSPARENT
    shadow=on
    position=top
    sticky=on
    padding_right=10
    padding_left=10
    corner_radius=9
    y_offset=9
    margin=10
    blur_radius=0
    font_smothing=on
)


defaults=(
    updates=when_shown
    icon.font="$FONT:Bold:14.0"
    icon.color=$ICON_COLOR
    icon.padding_left=$PADDINGS
    icon.padding_right=$PADDINGS
    label.font="$FONT:Semibold:13.0"
    label.color=$LABEL_COLOR
    label.padding_left=$PADDINGS
    label.padding_right=$PADDINGS
    padding_right=$PADDINGS
    padding_left=$PADDINGS
    background.height=30
    background.corner_radius=9
    popup.background.border_width=1
    popup.background.corner_radius=9
    popup.background.border_color=$POPUP_BORDER_COLOR
    popup.background.color=$POPUP_BACKGROUND_COLOR
    popup.blur_radius=0
    popup.background.shadow.drawing=on
)

sketchybar --bar "${bar[@]}"
sketchybar --default "${defaults[@]}"
sketchybar --trigger space_change --trigger windows_on_spaces

# Spaces
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10" "11" "12" "13" "14" "15")

sid=0
spaces=()
for i in "${!SPACE_ICONS[@]}"
do
    sid=$(($i+1))

    space=(
        associated_space=$sid
        icon=${SPACE_ICONS[i]}
        icon.padding_left=10
        icon.padding_right=15
        padding_left=2
        padding_right=2
        label.padding_right=20
        icon.highlight_color=$RED
        label.font="sketchybar-app-font:Regular:16.0"
        label.background.height=26
        label.background.drawing=on
        label.background.color=$BACKGROUND_2
        label.background.corner_radius=8
        label.drawing=off
        script="$PLUGIN_DIR/space.sh"
    )

    sketchybar --add space space.$sid left    \
        --set space.$sid "${space[@]}" \
        --subscribe space.$sid mouse.clicked
done

spaces=(
    background.color=$BACKGROUND_1
    background.border_color=$BACKGROUND_2
    background.border_width=1
    background.drawing=on
)

separator=(
    icon=􀆊
    icon.font="$FONT:Heavy:16.0"
    padding_left=15
    padding_right=15
    label.drawing=off
    associated_display=active
    click_script='yabai -m space --create && sketchybar --trigger space_change'
    icon.color=$WHITE
)

sketchybar --add bracket spaces '/space\..*/' \
    --set spaces "${spaces[@]}"        \
    --add item separator left          \
    --set separator "${separator[@]}"


FRONT_APP_SCRIPT='sketchybar --set $NAME label="$INFO" \
    --trigger space_change \
    --trigger windows_on_spaces '

yabai=(
    script="$PLUGIN_DIR/yabai.sh"
    label.drawing=off
    icon.drawing=off
    padding_left=0
    padding_right=0
    associated_display=active
)

front_app=(
    script="$FRONT_APP_SCRIPT"
    icon.drawing=off
    padding_left=0
    label.color=$WHITE
    label.font="$FONT:Black:12.0"
    associated_display=active
)

sketchybar --add event window_focus \
    --add event windows_on_spaces \
    --add item yabai left \
    --set yabai "${yabai[@]}" \
    --subscribe yabai window_focus \
    windows_on_spaces \
    mouse.clicked \
    --add item front_app left \
    --set front_app "${front_app[@]}" \
    --subscribe front_app front_app_switched

sketchybar --add event window_focus            \
    --add event windows_on_spaces       \
    --add item yabai left               \
    --set yabai "${yabai[@]}"           \
    --subscribe yabai window_focus      \
    windows_on_spaces \
    mouse.clicked     \
    --add item front_app left           \
    --set front_app "${front_app[@]}"   \
    --subscribe front_app front_app_switched

# Calendar
calendar=(
    icon=cal
    icon.font="$FONT:Black:12.0"
    icon.padding_right=0
    label.width=45
    label.align=right
    padding_left=15
    update_freq=30
    script="$PLUGIN_DIR/calendar.sh"
    # click_script="$PLUGIN_DIR/zen.sh"
)

sketchybar --add item calendar right       \
    --set calendar "${calendar[@]}" \
    --subscribe calendar system_woke


# Battery
battery=(
    script="$PLUGIN_DIR/battery.sh"
    icon.font="$FONT:Regular:19.0"
    padding_right=5
    padding_left=0
    label.drawing=off
    update_freq=120
    updates=on
)

sketchybar --add item battery right      \
    --set battery "${battery[@]}" \
    --subscribe battery power_source_change system_woke

# Volume
volume_slider=(
    script="$PLUGIN_DIR/volume.sh"
    updates=on
    label.drawing=off
    icon.drawing=off
    slider.highlight_color=$BLUE
    slider.background.height=5
    slider.background.corner_radius=3
    slider.background.color=$BACKGROUND_2
    slider.knob=􀀁
    slider.knob.drawing=off
)

volume_icon=(
    click_script="$PLUGIN_DIR/volume_click.sh"
    padding_left=10
    padding_right=0
    icon=$VOLUME_100
    icon.width=0
    icon.align=left
    icon.color=$GREY
    icon.font="$FONT:Regular:14.0"
    label.width=25
    label.align=left
    label.font="$FONT:Regular:14.0"
)


sketchybar --add slider volume right            \
    --set volume "${volume_slider[@]}"   \
    --subscribe volume volume_change     \
    mouse.clicked     \
    mouse.entered     \
    mouse.exited      \
    --add item volume_icon right         \
    --set volume_icon "${volume_icon[@]}"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
