#! /usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

BAR_HEIGHT=$(sketchybar --query bar 2>/dev/null | jq .height 2>/dev/null || echo 30)
BAR_HEIGHT=$((BAR_HEIGHT))  # Ensure it's a number.

SKETCHYBAR_Y_OFFSET=9
SKETCHYBAR_MARGIN=8

TOP_PADDING=$((SKETCHYBAR_Y_OFFSET + SKETCHYBAR_MARGIN))

yabai -m config external_bar all:$BAR_HEIGHT:0
yabai -m config top_padding $TOP_PADDING

yabai -m config \
    mouse_follows_focus       on \
    focus_follows_mouse       autofocus \
    window_zoom_persist       off \
    window_placement          second_child \
    window_shadow             float \
    window_opacity            on \
    window_opacity_duration   0.2 \
    active_window_opacity     1.0 \
    normal_window_opacity     0.8 \
    window_animation_duration 0.15 \
    window_animation_easing   ease_out_circ \
    split_ratio               0.5 \
    auto_balance              on \
    mouse_modifier            fn \
    mouse_action1             move \
    mouse_action2             resize \
    mouse_drop_action         swap \
    bottom_padding            8 \
    left_padding              8 \
    right_padding             8 \
    window_gap                8 \
    warp_cursor               focus \
    layout                    bsp

# Applications to float
FLOAT_APPS="^(Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|App Store|Steam|Raycast|ThinkBuddy|Activity Monitor|Finder|Monarch|MediaMate|NotchNook|Alcove|UTM)$"
yabai -m rule --add app="$FLOAT_APPS" manage=off

# Exclude system dialogs
SYSTEM_DIALOGS="^(System Preferences|System Settings|About This Mac|Print|Scanner|FaceTime)$"
yabai -m rule --add app="$SYSTEM_DIALOGS" manage=off

# Close notification windows
yabai -m signal --add event=window_created app="NotificationCenter" action="sleep 5; yabai -m window $YABAI_WINDOW_ID --close"

echo "yabai configuration loaded..."
